---
- name: create the domain
  become: yes
  command: "{{ path_vadddomain }} {{ domain.name }} {{ domain.password }}"
  args:
    creates: "{{ path_vpopmail_domains_dir }}{{ domain.name }}"
  notify:
    - restart dovecot
  tags:
    - always

- name: create the .qmail-default file for the domain
  become: yes
  template:
    src: templates/dot_qmail_default.j2
    dest: "{{ path_vpopmail_domains_dir }}/{{ domain.name }}/.qmail_default"
    owner: vpopmail
    group: vchkpw
    mode: 0644
  tags:
    - always

- name: process sets of role accounts
  include_tasks: do_create_role_accounts.yml
  vars:
    target_roleset: "{{ roleset }}"
    target_domain: "{{ domain }}"
  when: domain.rolesets is defined
  loop: "{{ domain.rolesets }}"
  loop_control:
    loop_var: roleset
  tags:
    - always

- name: create users
  include_tasks: do_create_user.yml
  vars:
    userdomain: "{{ domain.name }}"
    username: "{{ user.name }}"
    password: "{{ user.password }}"
    comment: "{{ user.comment | default('') }}"
    quota: "{{ user.quota | default('NOQUOTA') }}"
    filter: "{{ user.filter | default('no') }}"
    bounce: "{{ user.bounce | default('no') }}"
    delete: "{{ user.delete | default('no') }}"
    address: "{{ user.address | default('') }}"
    filtersets: "{{ user.filtersets | default(standard_filter_sets) }}"
    filterdirs: "{{ user.filterdirs | default(standard_filter_directories) }}"
  when: domain.users is defined
  loop: "{{ domain.users }}"
  loop_control:
    loop_var: user
  tags:
    - always
