---
- name: announce activity
  debug:
    msg: "Processing domain {{ domain.name }} ..."
  tags:
    - always

- name: create the domain
  become: yes
  command: "/home/vpopmail/bin/vadddomain {{ domain.name }} {{ domain.password }}"
  args:
    creates: "/home/vpopmail/domains/{{ domain.name }}"
  notify:
    - restart dovecot
  tags:
    - always

- name: create the .qmail-default file for the domain
  become: yes
  template:
    src: templates/dot_qmail_default.j2
    dest: /home/vpopmail/domains/{{ domain.name }}/.qmail_default
    owner: vpopmail
    group: vchkpw
    mode: 0644
  tags:
    - always

- name: process sets of role accounts
  include_tasks: do_create_role_accounts.yml
  vars:
    target_roleset: "{{ roleset }}"
    target_domain: "{{ domain }}"
  when: domain.rolesets is defined
  loop: "{{ domain.rolesets }}"
  loop_control:
    loop_var: roleset
  tags:
    - always
